apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
spec:
  serviceAccount: jenkins  
  containers:
  - name: docker
    image: docker:20.10.8-dind
    securityContext:
      privileged: true
    command:
      - cat
    tty: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "1"
        memory: "512Mi"
  - name: kubectl
    image: bitnami/kubectl:1.31.1
    securityContext:
      runAsUser: 1000
    command:
      - cat
    tty: true
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "1"
        memory: "512Mi"
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/agent
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
  - name: workspace-volume
    emptyDir: {}
