apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:20.10.8-dind
    securityContext:
      privileged: true
    command:
      - cat
    tty: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
